version: '3'
services:
  lidar_sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lidarsim
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Enable X11 forwarding
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer
    ports:
      - "11311:11311"
      - "3636:3636"
      - "9090:9090"
    tty: true
    stdin_open: true
    command: /rosstart/start-services.sh
  matlab:
    build:
      context: .
      dockerfile: DockerfileMatlab
    environment:
      - ADDITIONAL_PRODUCTS="ROS_Toolbox"
    ports:
      - "8888:8888"  # Expose port 8888 for web access if needed
    shm_size: 1024M  # Set shared memory size, which is important for performance
    command: ["-browser"]  # Start MATLAB with browser mode enabled
    tty: true  # Allocates a pseudo-TTY (similar to -t in Docker run)
    stdin_open: true  # Keeps stdin open (similar to -i in Docker run)
    restart: "no" 